console.log("hello");
console.log("hello");
console.log("hello");
console.log("hello");
try{
console.log(a);
}catch(error){
    console.log(error);
}
console.log("Shubham");
console.log("Shubham");
console.log("Shubham");
console.log("Shubham");